version: '3.6'
services:
  java:
    build: ./docker/java
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./server/java:/usr/java:cached
      - ./server/ABC:/usr/ABC:cached
    command: /bin/bash

  cpp:
    build: ./docker/cpp
    ports:
      - 3001:3001
    tty: true
    volumes:
      - ./server/cpp:/usr/cpp:cached
      - ./server/ABC:/usr/ABC:cached
    command: /bin/bash